### ISSUE TITLE
How to use model to generate trajectories

### ISSUE THREAD

**Issue by easonycliu** [benchoi93/TrajGen_GAIL#2]
I've trained a model with the given dataset, and saved the model to /Result folder, which is a .pt file. Then I want to use the model 
to generate new trajectories. Which function should I use?

**Comment by benchoi93** [comment]
If you are referring to TrajGAIL, there's a function called unroll_trajectory2 in the main file

![image](https://user-images.githubusercontent.com/28798606/169709681-039e983f-7420-4bd7-a283-bc1a5de5c389.png)

**Comment by easonycliu** [comment]
The generator is working now.
Many thanks!
