### ISSUE TITLE
It seems like the run_gail script is encountering an issue while executing

### ISSUE THREAD

**Issue by qfotcom** [benchoi93/TrajGen_GAIL#4]
![image](https://github.com/benchoi93/TrajGAIL/assets/103864251/970c2d57-5fa6-4a88-979d-cb902b896cce)
It seems like the run_gail script is encountering an issue while executing, despite other scripts like run_bc_mmc, run_bc_rnn, and demo_shortestpath running smoothly. Based on the error message, it doesn't appear to be an issue with the environment setup. Have you encountered this kind of problem before, and if so, how did you address it?

**Comment by wenjiwei** [comment]
Hello, I am also having the same problem as you, have you solved it, and I would be grateful if you could tell me the solution

**Comment by 313er** [comment]
Hello, I am also having the same problem as you, have you solved it？And I would be grateful if you could tell me the solution
